apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudbees-ci
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: cb-ci-argo
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.cloudbees.com/public/cloudbees'
    targetRevision: 3.18.0+9e7e10b4b576
    chart: cloudbees-core
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: OperationsCenter.Platform
          value: gke
        - name: OperationsCenter.HostName
          value: msuarez.argo.io
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions: []
